# 本地服务器配置
serves:
  port: 8080
request: 
  getConfig:
    method: post
    params: ~
  getAllApi:
    method: post
    params: ~
  getDoc:
    method: post
    params: ~
  login:
    method: post
    params: 
      userName: 'admin'
      password: '123456'
      token: 
        key: ''
        time: 30000
  
  
  
  



